# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= BlogBackend.config.postgres.host %>
  username: <%= BlogBackend.config.postgres.username %>
  password: <%= BlogBackend.config.postgres.password %>
  database: <%= BlogBackend.config.postgres.database %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default
  database: <%= BlogBackend.config.postgres.database %>_test

production:
  <<: *default

